- hosts: all
  gather_facts: False
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- hosts: all
  become: yes
  tasks:    
    - name: install pip
      apt:
        name: python-pip
        state: present
        update_cache: true
    - name: Install docker.py for usages
      pip:
        name: docker-py
        version: 1.10.6
        state: present

    #Installing docker for ubuntu 18.04
    - name: add Docker apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present        
    - name: add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: 'docker'
    - name: install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: true    
    - name: Copy docker dialogflow-rnd.keyfile.json    
      copy:
        # src: "{{ role_path }}/keyfile.json"
        src: /mnt/d/deployment/ansible/keyfile.json
        dest: /home/user/keyfile.json
        owner: eng        
        mode: 0644
        
    - name: login to docker registry
      become: yes
      shell: "docker login -u _json_key -p \"$(cat keyfile.json)\" https://gcr.io"

